#!/usr/bin/env node

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const ROOT = path.join(__dirname, '..');
const COMPLIANCE_DIR = path.join(ROOT, 'logs', 'compliance');
const HASH_LEDGER_PATH = path.join(COMPLIANCE_DIR, 'p4_registry_sign.hash');
const VALIDATION_REPORT_PATH = path.join(COMPLIANCE_DIR, 'p4_validation_report.json');

const PILLAR_FILES = [
  'p1_spatial_drift.bin',
  'p1_sensor_heartbeat.json',
  'p2_trajectory_bounds.json',
  'p2_mesh_convergence.bin',
  'p3_command_sanitization.log',
  'p3_failsafe_triggers.json',
  'p4_registry_sign.hash',
  'p4_validation_report.json',
  'p5_simulation_delta.json',
  'p5_inference_audit.bin',
];

function sha256Buffer(buffer) {
  return crypto.createHash('sha256').update(buffer).digest('hex');
}

function ensureParent(filePath) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
}

function ensureBaselineFile(relativePath) {
  const absolutePath = path.join(COMPLIANCE_DIR, relativePath);
  ensureParent(absolutePath);

  if (fs.existsSync(absolutePath)) {
    return { absolutePath, created: false };
  }

  const ext = path.extname(relativePath);
  if (ext === '.json') {
    fs.writeFileSync(absolutePath, `${JSON.stringify({ schemaVersion: 'ogen.compliance.v1', records: [] }, null, 2)}\n`);
  } else if (ext === '.log') {
    fs.writeFileSync(absolutePath, '[SYSTEM_INIT] compliance ledger scaffold\n');
  } else if (ext === '.hash') {
    fs.writeFileSync(absolutePath, '# generated by tools/parallel_check.js\n');
  } else {
    fs.writeFileSync(absolutePath, Buffer.from('4f47454e5f434f4d504c49414e43455f53434146464f4c44', 'hex'));
  }

  return { absolutePath, created: true };
}

function main() {
  const strict = process.argv.includes('--strict');
  fs.mkdirSync(COMPLIANCE_DIR, { recursive: true });

  const manifestValidationRaw = execFileSync('node', ['tools/validate_manifest.js', '--target', 'compliance'], {
    cwd: ROOT,
    encoding: 'utf8',
  });
  const manifestValidation = JSON.parse(manifestValidationRaw);

  const created = [];
  const files = [];

  PILLAR_FILES.forEach((relativePath) => {
    const outcome = ensureBaselineFile(relativePath);
    if (outcome.created) created.push(relativePath);

    const content = fs.readFileSync(outcome.absolutePath);
    const stats = fs.statSync(outcome.absolutePath);
    files.push({
      path: `logs/compliance/${relativePath}`,
      sha256: sha256Buffer(content),
      sizeBytes: stats.size,
      modifiedAt: stats.mtime.toISOString(),
    });
  });

  if (strict && created.length > 0) {
    throw new Error(`Missing compliance files created during strict run: ${created.join(', ')}`);
  }

  const hashLedger = files.map((entry) => `${entry.sha256}  ${entry.path}`).join('\n');
  fs.writeFileSync(HASH_LEDGER_PATH, `${hashLedger}\n`);

  const report = {
    status: 'ok',
    mode: strict ? 'strict' : 'repair',
    validatedAt: new Date().toISOString(),
    manifestValidation,
    created,
    files,
  };
  fs.writeFileSync(VALIDATION_REPORT_PATH, `${JSON.stringify(report, null, 2)}\n`);

  console.log(JSON.stringify({
    status: report.status,
    mode: report.mode,
    validatedAt: report.validatedAt,
    created: report.created.length,
    fileCount: report.files.length,
    manifestTarget: manifestValidation.target,
  }, null, 2));
}

try {
  main();
} catch (error) {
  console.error(`[PARALLEL CHECK] ${error.message}`);
  process.exitCode = 1;
}
